### ISSUE TITLE
TypeError highlight_elements() got an unexpected keyword argument 'strict' after upgrade to 8.0.1

### ISSUE THREAD

**Issue by ealap** [MarketSquare/robotframework-browser#1304]
**Describe the bug**
Execution of keyword `Fill Text` fails due to unexpected `strict` argument in `highlight_elements` function call

**To Reproduce**
1. Given version is 8.0.1
2. Then execute test that uses `Fill text` keyword

**Expected behavior**
Keyword `Fill text` would still be working as expected after upgrade

**Logs**
```
FAIL    TypeError: Evaluation.highlight_elements() got an unexpected keyword argument 'strict'
DEBUG    Traceback (most recent call last):
  File "/home/ealap/optimy/project/otm_automation/staging/.venv/qa_env/lib/python3.10/site-packages/Browser/browser.py", line 849, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/home/ealap/optimy/project/otm_automation/staging/.venv/qa_env/lib/python3.10/site-packages/robotlibcore.py", line 94, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "/home/ealap/optimy/project/otm_automation/staging/.venv/qa_env/lib/python3.10/site-packages/Browser/keywords/interaction.py", line 108, in fill_text
    self._fill_text(selector, txt, strict=self.strict_mode)
  File "/home/ealap/optimy/project/otm_automation/staging/.venv/qa_env/lib/python3.10/site-packages/Browser/keywords/interaction.py", line 632, in _fill_text
    self.library.highlight_elements(
```

**Desktop (please complete the following information):**
 - OS: Ubuntu x64 21.04
 - Browser: Any

**Additional context**
I think problem roots here
https://github.com/MarketSquare/robotframework-browser/blob/6f47fad7ac09a00e29ff4cb634a32e4c9b5d6fcd/Browser/keywords/evaluation.py#L57-L64

**Comment by aaltat** [comment]
This is unfortunate and true. There is bug. You can workaround the bug by disabling the highlight. 

@all-contributors please add @ealap for bug

**Comment by mkorpela** [comment]
Fixed in 1308
