### ISSUE TITLE
Wait For Promise will return exception when promise reached timeout exception

### ISSUE THREAD

**Issue by siongwai** [MarketSquare/robotframework-browser#3920]
**Describe the bug**
Issue happen on `19.0.1`

The keyword `Wait For    ${promise}` will have exception when reached timeout

**To Reproduce**
I have prepare the sample.robot.

```
*** Settings ***
Library     Browser


*** Variables ***
${host_url}     https://www.google.com
${url}          /


*** Test Cases ***
T1
    New Browser    headless=${False}    channel=chrome
    New Context    baseURL=${host_url}    viewport=${None}
    New Page    ${url}    wait_until=domcontentloaded

    # random wrong promise
    ${promise}    Promise To
    ...    Wait For Response
    ...    response => response.url().includes('UseCaseDefinitions') && response.request().method() === 'GET'

    Fill Text    form textarea    robotframework
    Keyboard Key    press    Enter

    Wait For    ${promise}
```

**Expected behavior**
keyword is working in 18.9.1

**Screenshots**
```
Traceback (most recent call last):
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\playwright.py", line 170, in grpc_channel
    yield playwright_pb2_grpc.PlaywrightStub(self._channel)
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 119, in _wait_for_http
    logger.debug(response.log)
                 ^^^^^^^^^^^^
AttributeError: '_MultiThreadedRendezvous' object has no attribute 'log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\browser.py", line 1241, in run_keyword
    raise e
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\browser.py", line 1230, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\robotlibcore.py", line 173, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\promises.py", line 249, in wait_for
    return promises[0].result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 232, in wait_for_response
    response = self._wait_for_http("Response", matcher, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 111, in _wait_for_http
    with self.playwright.grpc_channel() as stub:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\playwright.py", line 177, in grpc_channel
    raise AssertionError(str(error))
AssertionError: '_MultiThreadedRendezvous' object has no attribute 'log'
```

**Comment by aaltat** [comment]
Yeah, clearly regression related to fixing this one https://github.com/MarketSquare/robotframework-browser/issues/1815 

@allcontributors please add @siongwai for bugs

**Comment by aaltat** [comment]
Are you sure that exception is from 19.0 release? Because the exception 

```python
Traceback (most recent call last):
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\playwright.py", line 170, in grpc_channel
    yield playwright_pb2_grpc.PlaywrightStub(self._channel)
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 119, in _wait_for_http
    logger.debug(response.log)
                 ^^^^^^^^^^^^

```
Would match in 18.9 release  https://github.com/MarketSquare/robotframework-browser/blob/v18.9.1/Browser/keywords/network.py#L119 The 19.0 release does not anymore have `_wait_for_http` method. 

I tried your example test case and it fails normally within a timeout, both with 18.9 and 19.0 release. Also tried both `Wait For Response` and `Wait For Request` keywords and both fails with a timeout on both 18,9 and 19.0 release. 

Therefore I do not know how to fix your problem, because I can not reproduced it.

**Comment by Snooz82** [comment]
@aaltat that matches 19.0.0. 
But 19.0.1 has this in line 120.

however, we can not reproduce. sorry.

**Comment by siongwai** [comment]
Thank you for checking. I cannot reproduce as well after reinstall 19.0.1.

I will close this bug now,
