### ISSUE TITLE
Got TypeError: activePage.locator is not a function when using variable as parameter on "Click" keyword

### ISSUE THREAD

**Issue by laguna357** [MarketSquare/robotframework-browser#1475]
When using variable as parameter on "Click" keyword.
For example
`FOR    ${num}    IN RANGE    1    51`
`    Click    xpath=//*[@id="grid"]/div[text()="${num}"]`
`END`
It used to work on version  2.5.0. After I update to current version I got error message
`TypeError: activePage.locator is not a function` 

**To Reproduce**
`New Browser    chromium    headless=false`
`New Page     http://zzzscore.com/1to50/en/`
`FOR    ${num}    IN RANGE    1    51`
`    Click    xpath=//*[@id="grid"]/div[text()="${num}"]`
`END`

**Desktop**
MacOS Catalina 10.15.7

**Comment by aaltat** [comment]
@allcontributors please add @laguna357 for bugs

**Comment by aaltat** [comment]
I tried the example, but I can not reproduce the issue with current development version. I tried both strict and not strict modes. If this is still a problem, please provide more details. Also please try use clean installation with venv.

**Comment by aaltat** [comment]
One thing came to my mind, did you run `rfbrowser init` after the update?

**Comment by laguna357** [comment]
> One thing came to my mind, did you run `rfbrowser init` after the update?

No, I did not.
Just seen the update instructions.
Should I retry again with proper update step ?

**Comment by laguna357** [comment]
> One thing came to my mind, did you run `rfbrowser init` after the update?

Sorry, I did not.
Just tried update to v10.0.2 follow by update instruction step 2 and 3. It's work !!
BTW I also tried with v10.0.3. It's work even I did not do step 2 and 3.
Sorry for troubled you guys.

**Comment by aaltat** [comment]
You should always do all the steps,  because it ensures that node dependencies are installed correctly.
